packages:
  - 'packages/*'
  - 'dialect/*'
  - 'apps/*'

# Required for parser (native bindings)
onlyBuiltDependencies:
  - tree-sitter

overrides:
  vite: ^7.3.5

# Block installs of packages published less than 1 day ago
minimumReleaseAge: 1440
