/*
 * Copyright (c) 2026, Salesforce, Inc.
 * All rights reserved.
 * SPDX-License-Identifier: Apache-2.0
 * For full license text, see the LICENSE file in the repo root or https://www.apache.org/licenses/LICENSE-2.0
 */

/**
 * The list of `.agent` source fixtures driving both the parity test
 * (`compare-all.test.ts`) and the regen script (`scripts/regen-fixtures.ts`).
 * Keeping them in a shared module ensures the two stay in sync.
 *
 * For each entry, the parity test reads expected snake-case JSON from
 * `test/fixtures/expected/<base>.snake.json` and camelCase JSON from
 * `test/fixtures/expected/<base>.camel.json`, where `<base>` is the
 * filename with the `.agent` suffix stripped.
 */
export const FIXTURES: string[] = [
  // Original fixtures
  'hello_world.agent',
  'weather.agent',
  'adecco.agent',
  'deep_supervision.agent',
  'aron_steel_thread.agent',
  'router_node_template.agent',
  'matrix.agent',
  'multi-line-descriptions.agent',
  'pronto_booth_readiness.agent',
  'pronto_customer_support.agent',
  'after_reasoning_delegate.agent',
  'siemens.agent',
  'access_with_vcra.agent',
  // New fixtures from Python repo
  'adecco_current.agent',
  'appointment_scheduler.agent',
  'aronscript.agent',
  'basic_topic.agent',
  'case_escalation_bot.agent',
  'claim_processing_assistant.agent',
  'conditional_runtime_test.agent',
  'csa.agent',
  'employee_agent.agent',
  'employee_agent_with_none_user.agent',
  'field_service_scheduler.agent',
  'hyperclassifier_model.agent',
  'inventory_management_bot.agent',
  'knowledge_search_assistant.agent',
  'lead_qualification_bot.agent',
  'loan_application_assistant.agent',
  'null_variable_assignments.agent',
  'opportunity_management_bot.agent',
  'order_tracking_assistant.agent',
  'post_action_conditionals.agent',
  'pricing_configuration_assistant.agent',
  'quality_control_assistant.agent',
  'service_appointment_scheduler.agent',
  'start_template.agent',
  'two_topic.agent',
  // Integration scripts from Python repo
  'helloworld1.agent',
  'helloworld2.agent',
  'simple-ordering.agent',
  'weather-v0.1.0.agent',
  // Numbered fixtures (100 complex scripts)
  '001_loan_origination.agent',
  '002_mortgage_processing.agent',
  '003_credit_scoring.agent',
  '004_investment_portfolio.agent',
  '005_treasury_management.agent',
  '006_fraud_detection.agent',
  '007_tax_compliance.agent',
  '008_payment_reconciliation.agent',
  '009_wealth_advisory.agent',
  '010_risk_assessment.agent',
  '011_patient_intake.agent',
  '012_clinical_trial.agent',
  '013_prescription_mgmt.agent',
  '014_insurance_claim_health.agent',
  '015_appointment_scheduling.agent',
  '016_lab_results.agent',
  '017_discharge_planning.agent',
  '018_referral_management.agent',
  '019_chronic_care.agent',
  '020_mental_health.agent',
  '021_order_fulfillment.agent',
  '022_inventory_control.agent',
  '023_customer_loyalty.agent',
  '024_product_return.agent',
  '025_price_matching.agent',
  '026_gift_registry.agent',
  '027_subscription_mgmt.agent',
  '028_vendor_onboarding.agent',
  '029_flash_sale.agent',
  '030_warranty_processing.agent',
  '031_incident_mgmt.agent',
  '032_change_request.agent',
  '033_asset_tracking.agent',
  '034_license_mgmt.agent',
  '035_security_audit.agent',
  '036_capacity_planning.agent',
  '037_deploy_pipeline.agent',
  '038_backup_recovery.agent',
  '039_network_monitoring.agent',
  '040_access_control.agent',
  '041_recruitment_pipeline.agent',
  '042_employee_onboarding.agent',
  '043_performance_review.agent',
  '044_leave_management.agent',
  '045_compensation_planning.agent',
  '046_benefits_enrollment.agent',
  '047_training_mgmt.agent',
  '048_succession_planning.agent',
  '049_exit_process.agent',
  '050_timesheet_approval.agent',
  '051_policy_underwriting.agent',
  '052_claims_adjudication.agent',
  '053_renewal_processing.agent',
  '054_premium_calculation.agent',
  '055_coverage_verification.agent',
  '056_beneficiary_mgmt.agent',
  '057_damage_assessment.agent',
  '058_fraud_investigation.agent',
  '059_compliance_review.agent',
  '060_reinsurance_mgmt.agent',
  '061_property_listing.agent',
  '062_tenant_screening.agent',
  '063_lease_management.agent',
  '064_maintenance_request.agent',
  '065_property_valuation.agent',
  '066_commission_tracking.agent',
  '067_showing_scheduler.agent',
  '068_closing_process.agent',
  '069_inspection_mgmt.agent',
  '070_hoa_compliance.agent',
  '071_booking_management.agent',
  '072_itinerary_planning.agent',
  '073_loyalty_rewards.agent',
  '074_cancellation_processing.agent',
  '075_group_travel.agent',
  '076_travel_insurance.agent',
  '077_visa_application.agent',
  '078_expense_reporting.agent',
  '079_hotel_management.agent',
  '080_flight_rebooking.agent',
  '081_production_scheduling.agent',
  '082_quality_inspection.agent',
  '083_supply_chain_mgmt.agent',
  '084_equipment_maintenance.agent',
  '085_raw_material.agent',
  '086_batch_tracking.agent',
  '087_safety_compliance.agent',
  '088_energy_management.agent',
  '089_warehouse_ops.agent',
  '090_shipping_logistics.agent',
  '091_permit_processing.agent',
  '092_license_renewal.agent',
  '093_benefit_application.agent',
  '094_compliance_enforcement.agent',
  '095_public_records.agent',
  '096_grant_management.agent',
  '097_voter_registration.agent',
  '098_emergency_response.agent',
  '099_procurement.agent',
  '100_citizen_feedback.agent',
  // Edge case fixtures (100 scripts)
  'edge_action_after_reasoning.agent',
  'edge_action_alias_targets.agent',
  'edge_action_apex.agent',
  'edge_action_api.agent',
  'edge_action_available_when.agent',
  'edge_action_before_reasoning.agent',
  'edge_action_complex_types.agent',
  'edge_action_confirmation.agent',
  'edge_action_flow.agent',
  'edge_action_invocable.agent',
  'edge_action_list_io.agent',
  'edge_action_many.agent',
  'edge_action_mixed_targets.agent',
  'edge_action_mcp_targets.agent',
  'edge_action_no_description.agent',
  'edge_action_no_inputs.agent',
  'edge_action_no_outputs.agent',
  'edge_action_placeholder.agent',
  'edge_action_set_many.agent',
  'edge_action_set_variables_util.agent',
  'edge_action_standard_invocable.agent',
  'edge_action_with_ellipsis.agent',
  'edge_action_with_literals.agent',
  'edge_action_with_variables.agent',
  'edge_cond_action_conditional.agent',
  'edge_cond_after_reasoning.agent',
  'edge_cond_before_reasoning.agent',
  'edge_cond_boolean_ops.agent',
  'edge_cond_comparison_ops.agent',
  'edge_cond_if_else.agent',
  'edge_cond_is_none.agent',
  'edge_cond_multiple_branches.agent',
  'edge_cond_nested.agent',
  'edge_cond_transition_conditional.agent',
  'edge_config_all_fields.agent',
  'edge_config_debug.agent',
  'edge_config_enhanced_logs.agent',
  'edge_config_minimal.agent',
  'edge_conn_all_surfaces.agent',
  'edge_conn_custom.agent',
  'connection_inputs.agent',
  'connection_additional_system_instructions.agent',
  'edge_conn_messaging.agent',
  'edge_conn_messaging_full.agent',
  'edge_conn_messaging_routing.agent',
  'edge_conn_multiple.agent',
  'edge_conn_routing.agent',
  'edge_conn_service_email.agent',
  'edge_conn_slack.agent',
  'edge_conn_slack_routing.agent',
  'edge_conn_voice.agent',
  // TODO (@sophie-guan, @setu-shah): Uncomment when compilation is updated
  'edge_conn_customizable.agent',
  'edge_directive_hyperclassifier.agent',
  'edge_education_enrollment.agent',
  'edge_employee_agent.agent',
  'edge_empty_messages.agent',
  'edge_end_session_basic.agent',
  'edge_escalation_basic.agent',
  'edge_escalation_conditional.agent',
  'edge_escalation_in_after.agent',
  'edge_escalation_multi_topic.agent',
  'edge_escalation_with_desc.agent',
  'edge_financial_kyc.agent',
  'edge_healthcare_scheduling.agent',
  'edge_hr_onboarding.agent',
  'edge_hyperclassifier_actions.agent',
  'edge_hyperclassifier_basic.agent',
  'edge_hyperclassifier_knowledge.agent',
  'edge_insurance_claims.agent',
  'edge_knowledge_and_actions.agent',
  'edge_knowledge_basic.agent',
  'edge_knowledge_citations.agent',
  'edge_knowledge_escalation_combo.agent',
  'edge_knowledge_in_topic.agent',
  'edge_knowledge_with_clauses.agent',
  'edge_locale_multiple.agent',
  'edge_locale_non_us.agent',
  'edge_logistics_tracking.agent',
  'edge_long_messages.agent',
  'edge_many_topics.agent',
  'edge_message_variables.agent',
  'edge_real_estate_inquiry.agent',
  'edge_restaurant_reservations.agent',
  'edge_retail_returns.agent',
  'edge_router_basic.agent',
  'edge_router_complex.agent',
  'edge_router_escalation.agent',
  'edge_router_many_routes.agent',
  'edge_router_model_config.agent',
  'edge_router_with_topics.agent',
  'edge_single_topic.agent',
  'edge_telecom_support.agent',
  'edge_topic_circular.agent',
  'edge_topic_deep_chain.agent',
  'edge_topic_escalation_flow.agent',
  'edge_topic_hub.agent',
  'edge_topic_long_description.agent',
  'edge_topic_minimal.agent',
  'edge_topic_no_actions.agent',
  'edge_topic_no_reasoning.agent',
  'edge_vars_all_types.agent',
  'edge_vars_custom_fields.agent',
  'edge_vars_defaults.agent',
  'edge_vars_linked_types.agent',
  'edge_vars_lists.agent',
  'edge_vars_many.agent',
  'edge_vars_mixed.agent',
  'edge_vars_no_description.agent',
  'edge_vars_null_defaults.agent',
  'edge_vars_object_complex.agent',
  // Connected agent fixtures
  'connected_subagent_tool.agent',
  'delegate_escalation.agent',
  // New syntax fixtures
  'new_syntax_two_topic.agent',
  'new_syntax_action_flow.agent',
  'new_syntax_hyperclassifier.agent',
  'mixed_syntax_multi_topic.agent',
  // Context block fixtures
  'context_memory_agent.agent',
  'context_full_agent.agent',
  // Recommended prompts fixtures
  'recommendations_agent.agent',
  // Constant value fixtures
  'constant_values_edge_cases.agent',
  'constant_values_literals.agent',
  'constant_values_mixed.agent',
  // Custom subagent (commerce shopper) fixtures
  'commerce_shopper_agent.agent',
  'byon_minimal.agent',
  'byon_only_start_agent.agent',
  'byon_node_accesstoken.agent',
  'byon_shopper_agent.agent',
  'shopper_prod.agent',
  // Custom subagent (tableau analyze data) fixture
  'tableau_analyze_data.agent',
  // Connection fixtures
  'connection_with_unified_email.agent',
  // Collect (gather one field at a time) fixtures
  'collect_patient_intake.agent',
  // Collect inside if (branching + branch convergence)
  'collect_comms_branching.agent',
];

/**
 * Strip the `.agent` suffix to get the base used for fixture filenames.
 */
export function fixtureBase(agentFile: string): string {
  return agentFile.replace(/\.agent$/, '');
}
